name: prod-environment
on:  
  push:
    tags:
      - '*'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        run: |
         touch .env
         echo TAG=${{ steps.meta.outputs.tags }} >> .env  
         pwd .env  

      - name: Build docker
        run: |
         echo ---Building and starting up docker---
         docker-compose -p client up -d
         echo ---Containers up---

