name: prod-environment
on:  
  push:
    tags:
      - '*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Compose
        env:
          TAG: ${GITHUB_REF#refs/*/}
        
        run: |
         touch .env     
         echo "TAG=${{env.TAG}}" >> .env 
         echo ---Contenido de .env---
         cat .env
         
         echo ---Building and starting up docker---
         docker-compose -p client up -d
         echo ---Containers up---