name: prod-environment
on:  
  push:
    tags:
      - '*'
env:
  TAG: ${GITHUB_REF#refs/tags/*/}

jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest    
    steps:
    - name: show TAG
      run: echo "The TAG is:${{env.TAG}}" 
        
    - uses: actions/checkout@main
    - name: build and push to docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}