name: prod-environment
on:  
  push:
    tags:
      - '*'
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest    
    steps:    
    - uses: actions/checkout@v2
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
          images: vboard/vboard-ws
    - name: build and push to docker
    - uses: docker/build-push-action@v2
      with:
        context: vboard-ws
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tags: server.${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Validating the image built can start without any error
      run: docker run -e SPRING_PROFILES_ACTIVE=test -e EXIT_AFTER_INIT=true vboard/vboard-ws:${{ steps.meta.outputs.version }}    
    
    - name: Clean Up
      run: |
        docker image prune --force 


        