name: prod-environment
on:  
  push:
    tags:
      - '*'
env:
  TAG: ""

jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@main
    - name: build and push to docker
      uses: docker/build-push-action@v1
    - name: tag name
        ## Reference your environment variables
      run: echo "The TAG is:${{env.TAG}}"

      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
