name: prod-environment
on:  
  push:
    tags:
      - '*'
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest    
    steps:    
    - uses: actions/checkout@v2
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
          images: xx/xx
    - name: build and push to docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tags: server.${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Clean Up
      run: |
        docker image prune --force 


        